// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcuUEhQcNcdYRaT32TVzAJQ62HB8jqZjs',
    appId: '1:399233317286:web:8b51cbd7fa82bfe078f767',
    messagingSenderId: '399233317286',
    projectId: 'musicapp-1922c',
    authDomain: 'musicapp-1922c.firebaseapp.com',
    databaseURL: 'https://musicapp-1922c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'musicapp-1922c.appspot.com',
    measurementId: 'G-PSRMBSRH4X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqOQTb-ObiIANKdQBQoM3Z2DVa5DwFTf8',
    appId: '1:399233317286:android:9f79083064cc8d7078f767',
    messagingSenderId: '399233317286',
    projectId: 'musicapp-1922c',
    databaseURL: 'https://musicapp-1922c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'musicapp-1922c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzO1JdeKQfTjt9sCOp_WQwZ8Rof-5R5R4',
    appId: '1:399233317286:ios:9416427fd7d39af078f767',
    messagingSenderId: '399233317286',
    projectId: 'musicapp-1922c',
    databaseURL: 'https://musicapp-1922c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'musicapp-1922c.appspot.com',
    iosClientId: '399233317286-bvvlepm1k902bcuqj4l01bmsqc42nmku.apps.googleusercontent.com',
    iosBundleId: 'com.example.doAnMusicApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzO1JdeKQfTjt9sCOp_WQwZ8Rof-5R5R4',
    appId: '1:399233317286:ios:9416427fd7d39af078f767',
    messagingSenderId: '399233317286',
    projectId: 'musicapp-1922c',
    databaseURL: 'https://musicapp-1922c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'musicapp-1922c.appspot.com',
    iosClientId: '399233317286-bvvlepm1k902bcuqj4l01bmsqc42nmku.apps.googleusercontent.com',
    iosBundleId: 'com.example.doAnMusicApp1',
  );
}
